name: Generate ASCII Artwork

on: push

jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:
            - name: Install Cowsay
              run: sudo apt update && sudo apt install -y cowsay
            - name: Execute Cowasay CMD
              run:  cowsay -f dragon "Run for cover, I am a DRAGON...RAWR" >> dragon.txt
            - name: Uplaod dragond.txt file
              uses: actions/upload-artifact@v4
              with:
                name: dragon-text-file
                path: dragon.txt
    test_job_2:
        runs-on: ubuntu-latest
        needs: [build_job_1]
        steps:
            - name: Download dragond.txt file
              uses: actions/download-artifact@v4
              with:
                name: dragon-text-file
            - name: Test file exists
              run: grep -i "dragon" dragon.txt
    deploy_job_3:
        needs: [test_job_2]
        runs-on: ubuntu-latest
        steps:
            - name: Download dragond.txt file
              uses: actions/download-artifact@v4
              with:
                name: dragon-text-file
            - name: Read file
              run: cat ./dragon.txt